import Footer from "./Footer";
import REA from "./REA";
import Hero from "./Hero";
import Navbar from "./Navbar";
import WGT from "./WGT";
import Blogs from "./Blogs";
import Rigester from "./Rigester";
import GetStared from "./GetStared";
import Componies from "./Componies";
import Future from "./Future";
import InputForm from "./InputForm";
import WgbtCard from "./WgbtCard";
export {Footer,REA,Hero,Navbar, WGT,Blogs,Rigester,GetStared,Componies,Future, InputForm,WgbtCard}